import type { Artisan, ServiceCategory, Booking, UserProfile } from './types';

export const BRAND_NAME = 'NaijaHandy';
export const BRAND_TAGLINE = 'Find skilled artisans near you — fast, trusted, Naija.';
export const CONTACT_EMAIL = 'hello@naijahandy.ng';
export const CONTACT_PHONE = '+234 800 NAJAHANDY';

export const CATEGORIES: ServiceCategory[] = [
  { id: 'all', name: 'All Services', icon: 'Sparkles', description: 'Browse all artisans', count: 48 },
  { id: 'electrical', name: 'Electrical', icon: 'Zap', description: 'Electricians & wiring experts', count: 8 },
  { id: 'plumbing', name: 'Plumbing', icon: 'Droplets', description: 'Plumbers & pipe fitters', count: 6 },
  { id: 'painting', name: 'Painting', icon: 'PaintBucket', description: 'Painters & decorators', count: 7 },
  { id: 'carpentry', name: 'Carpentry', icon: 'Hammer', description: 'Carpenters & woodworkers', count: 5 },
  { id: 'mechanics', name: 'Mechanics', icon: 'Wrench', description: 'Auto & machinery repair', count: 6 },
  { id: 'construction', name: 'Construction', icon: 'Building2', description: 'Builders & masons', count: 9 },
  { id: 'cleaning', name: 'Cleaning', icon: 'SprayCan', description: 'Home & office cleaning', count: 7 },
];

export const ARTISANS: Artisan[] = [
  {
    id: 'a1',
    name: 'Chidi Okonkwo',
    profession: 'Master Electrician',
    category: 'electrical',
    location: 'Ikeja, Lagos',
    city: 'Lagos',
    state: 'Lagos',
    rating: 4.8,
    reviewCount: 124,
    priceRange: { min: 5000, max: 25000 },
    bio: 'Over 15 years of experience in residential and commercial electrical installations, repairs, and maintenance. Fully licensed and insured.',
    verified: true,
    available: true,
    yearsExperience: 15,
    phone: '+234 802 345 6789',
    email: 'chidi.okonkwo@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Chidi',
    coverImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80',
    ],
    services: [
      { name: 'Full House Wiring', description: 'Complete electrical wiring for new homes', price: 25000, duration: '2-3 days' },
      { name: 'Fault Repair', description: 'Diagnose and fix electrical faults', price: 5000, duration: '1-2 hours' },
      { name: 'Lighting Installation', description: 'Install indoor and outdoor lighting fixtures', price: 8000, duration: '3-4 hours' },
    ],
    reviews: [
      { id: 'r1', userName: 'Amara Okafor', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Amara', rating: 5, date: '2025-03-15', text: 'Chidi did an excellent job wiring our new office. Professional and thorough.' },
      { id: 'r2', userName: 'Femi Adeyemi', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Femi', rating: 4, date: '2025-02-28', text: 'Quick response and fair pricing. Fixed our faulty switchboard in no time.' },
    ],
    tags: ['Residential', 'Commercial', 'Emergency', 'Certified'],
    completedJobs: 340,
  },
  {
    id: 'a2',
    name: 'Ngozi Eze',
    profession: 'Plumbing Specialist',
    category: 'plumbing',
    location: 'Surulere, Lagos',
    city: 'Lagos',
    state: 'Lagos',
    rating: 4.6,
    reviewCount: 89,
    priceRange: { min: 4000, max: 20000 },
    bio: 'Reliable and experienced plumber handling everything from leaky faucets to full bathroom installations. Same-day service available.',
    verified: true,
    available: true,
    yearsExperience: 10,
    phone: '+234 803 456 7890',
    email: 'ngozi.eze@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ngozi',
    coverImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80',
      'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&q=80',
    ],
    services: [
      { name: 'Leak Repair', description: 'Fix leaking pipes, faucets, and toilets', price: 4000, duration: '1-2 hours' },
      { name: 'Bathroom Installation', description: 'Full bathroom plumbing installation', price: 20000, duration: '2-3 days' },
      { name: 'Drain Cleaning', description: 'Unclog drains and sewer lines', price: 6000, duration: '1-2 hours' },
    ],
    reviews: [
      { id: 'r3', userName: 'Tunde Bakare', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Tunde', rating: 5, date: '2025-03-10', text: 'Ngozi fixed our burst pipe within an hour. Highly recommend!' },
      { id: 'r4', userName: 'Chioma Nwosu', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Chioma', rating: 4, date: '2025-02-20', text: 'Good work on our bathroom renovation. Punctual and tidy.' },
    ],
    tags: ['Residential', 'Emergency', 'Same-day', 'Installation'],
    completedJobs: 215,
  },
  {
    id: 'a3',
    name: 'Segun Alabi',
    profession: 'Painter & Decorator',
    category: 'painting',
    location: 'Victoria Island, Lagos',
    city: 'Lagos',
    state: 'Lagos',
    rating: 4.7,
    reviewCount: 156,
    priceRange: { min: 8000, max: 50000 },
    bio: 'Creative painter with 8 years of experience in interior and exterior painting, wall finishes, and decorative coatings.',
    verified: true,
    available: false,
    yearsExperience: 8,
    phone: '+234 805 678 9012',
    email: 'segun.alabi@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Segun',
    coverImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&q=80',
      'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&q=80',
    ],
    services: [
      { name: 'Interior Painting', description: 'Full room painting with premium paint', price: 25000, duration: '2-3 days' },
      { name: 'Exterior Painting', description: 'House exterior painting and weatherproofing', price: 50000, duration: '4-5 days' },
      { name: 'Wall Texturing', description: 'Decorative wall textures and finishes', price: 15000, duration: '1-2 days' },
    ],
    reviews: [
      { id: 'r5', userName: 'Yemi Ogunlesi', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Yemi', rating: 5, date: '2025-03-05', text: 'Transformed our living room with beautiful textured walls. Amazing work!' },
      { id: 'r6', userName: 'Kehinde Salami', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Kehinde', rating: 5, date: '2025-02-18', text: 'Very professional team. Finished on time and within budget.' },
    ],
    tags: ['Interior', 'Exterior', 'Decorative', 'Residential'],
    completedJobs: 420,
  },
  {
    id: 'a4',
    name: 'Musa Bello',
    profession: 'Carpenter & Furniture Maker',
    category: 'carpentry',
    location: 'Kaduna',
    city: 'Kaduna',
    state: 'Kaduna',
    rating: 4.9,
    reviewCount: 72,
    priceRange: { min: 10000, max: 80000 },
    bio: 'Master carpenter specializing in custom furniture, kitchen cabinets, and wood fittings. Each piece is handcrafted with care.',
    verified: true,
    available: true,
    yearsExperience: 20,
    phone: '+234 806 789 0123',
    email: 'musa.bello@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Musa',
    coverImage: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=400&q=80',
      'https://images.unsplash.com/photo-1565793979006-8f7e0b7e7c31?w=400&q=80',
    ],
    services: [
      { name: 'Custom Furniture', description: 'Bespoke tables, chairs, cabinets and more', price: 50000, duration: '1-2 weeks' },
      { name: 'Kitchen Cabinets', description: 'Custom kitchen cabinet design and installation', price: 80000, duration: '1-2 weeks' },
      { name: 'Wood Repairs', description: 'Repair and restoration of wooden furniture', price: 10000, duration: '1-2 days' },
    ],
    reviews: [
      { id: 'r7', userName: 'Zainab Abdullah', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Zainab', rating: 5, date: '2025-03-01', text: 'Musa built us a stunning dining table. The craftsmanship is incredible.' },
      { id: 'r8', userName: 'Ibrahim Danjuma', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ibrahim', rating: 5, date: '2025-02-10', text: 'Best carpenter in Kaduna. Period.' },
    ],
    tags: ['Custom', 'Furniture', 'Cabinets', 'Restoration'],
    completedJobs: 560,
  },
  {
    id: 'a5',
    name: 'Bisi Ogunlade',
    profession: 'Auto Mechanic',
    category: 'mechanics',
    location: 'Ibadan',
    city: 'Ibadan',
    state: 'Oyo',
    rating: 4.5,
    reviewCount: 98,
    priceRange: { min: 3000, max: 35000 },
    bio: `Certified auto mechanic with expertise in all vehicle makes. From routine servicing to engine overhaul, I've got you covered.`,
    verified: true,
    available: true,
    yearsExperience: 12,
    phone: '+234 807 890 1234',
    email: 'bisi.ogunlade@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Bisi',
    coverImage: 'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?w=400&q=80',
      'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=400&q=80',
    ],
    services: [
      { name: 'Oil Change & Service', description: 'Full oil change and basic service', price: 8000, duration: '1-2 hours' },
      { name: 'Engine Diagnostics', description: 'Computer diagnostics and fault finding', price: 5000, duration: '1 hour' },
      { name: 'Brake Repair', description: 'Brake pad replacement and brake system repair', price: 15000, duration: '2-3 hours' },
    ],
    reviews: [
      { id: 'r9', userName: 'Dayo Akinlade', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Dayo', rating: 4, date: '2025-02-25', text: 'Fair prices and honest work. My car has never run better.' },
      { id: 'r10', userName: 'Funmi Ojo', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Funmi', rating: 5, date: '2025-02-05', text: `Great mechanic! Fixed my transmission issue when others couldn't.` },
    ],
    tags: ['Diagnostics', 'Repair', 'Servicing', 'All Makes'],
    completedJobs: 680,
  },
  {
    id: 'a6',
    name: 'Emeka Nwankwo',
    profession: 'General Contractor',
    category: 'construction',
    location: 'Enugu',
    city: 'Enugu',
    state: 'Enugu',
    rating: 4.7,
    reviewCount: 143,
    priceRange: { min: 15000, max: 200000 },
    bio: 'Full-service general contractor handling residential and commercial construction projects from foundation to finishing.',
    verified: true,
    available: true,
    yearsExperience: 18,
    phone: '+234 808 901 2345',
    email: 'emeka.nwankwo@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Emeka',
    coverImage: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&q=80',
      'https://images.unsplash.com/photo-1541888946425-d81bbfd58731?w=400&q=80',
    ],
    services: [
      { name: 'House Construction', description: 'Complete residential building construction', price: 200000, duration: '3-6 months' },
      { name: 'Renovation', description: 'Home renovation and remodeling', price: 80000, duration: '2-4 weeks' },
      { name: 'Foundation Work', description: 'Foundation laying and concrete work', price: 50000, duration: '1-2 weeks' },
    ],
    reviews: [
      { id: 'r11', userName: 'Adaobi Ani', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Adaobi', rating: 5, date: '2025-01-20', text: 'Emeka built our family home. Quality work and excellent project management.' },
      { id: 'r12', userName: 'Chuka Okafor', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Chuka', rating: 4, date: '2025-01-05', text: 'Solid work on our office renovation. Slightly over budget but worth it.' },
    ],
    tags: ['Residential', 'Commercial', 'Renovation', 'Project Management'],
    completedJobs: 95,
  },
  {
    id: 'a7',
    name: 'Aisha Mohammed',
    profession: 'Cleaning Expert',
    category: 'cleaning',
    location: 'Abuja',
    city: 'Abuja',
    state: 'FCT',
    rating: 4.4,
    reviewCount: 67,
    priceRange: { min: 5000, max: 25000 },
    bio: 'Professional cleaning service for homes and offices. Eco-friendly products and thorough attention to detail.',
    verified: false,
    available: true,
    yearsExperience: 5,
    phone: '+234 809 012 3456',
    email: 'aisha.mohammed@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Aisha',
    coverImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80',
    ],
    services: [
      { name: 'Deep Cleaning', description: 'Full house deep cleaning service', price: 15000, duration: '4-6 hours' },
      { name: 'Office Cleaning', description: 'Commercial office cleaning', price: 25000, duration: '3-4 hours' },
      { name: 'Move-out Cleaning', description: 'End of tenancy cleaning', price: 20000, duration: '4-5 hours' },
    ],
    reviews: [
      { id: 'r13', userName: 'Peter Oche', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Peter', rating: 4, date: '2025-03-08', text: 'Very thorough cleaning. Our office looks spotless.' },
    ],
    tags: ['Residential', 'Commercial', 'Eco-friendly', 'Deep Clean'],
    completedJobs: 180,
  },
  {
    id: 'a8',
    name: 'Tunde Mustapha',
    profession: 'AC & Refrigeration Technician',
    category: 'electrical',
    location: 'Port Harcourt',
    city: 'Port Harcourt',
    state: 'Rivers',
    rating: 4.6,
    reviewCount: 54,
    priceRange: { min: 6000, max: 30000 },
    bio: 'Specialized in air conditioning installation, repair, and maintenance. Also handles refrigeration systems for homes and businesses.',
    verified: true,
    available: true,
    yearsExperience: 9,
    phone: '+234 810 123 4567',
    email: 'tunde.mustapha@email.com',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=TundeM',
    coverImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    portfolio: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80',
    ],
    services: [
      { name: 'AC Installation', description: 'Split AC and central AC installation', price: 20000, duration: '3-4 hours' },
      { name: 'AC Repair', description: 'Diagnose and fix AC issues', price: 8000, duration: '1-2 hours' },
      { name: 'AC Servicing', description: 'Full AC maintenance and gas refill', price: 12000, duration: '1-2 hours' },
    ],
    reviews: [
      { id: 'r14', userName: 'Helen George', userAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Helen', rating: 5, date: '2025-03-12', text: 'Quick AC repair on a Sunday. Saved us from the heat!' },
    ],
    tags: ['AC', 'Refrigeration', 'Installation', 'Emergency'],
    completedJobs: 310,
  },
];

export const SAMPLE_BOOKINGS: Booking[] = [
  { id: 'b1', artisanId: 'a1', artisanName: 'Chidi Okonkwo', artisanProfession: 'Master Electrician', artisanAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Chidi', customerName: 'You', date: '2025-04-10', time: '10:00 AM', description: 'Full house wiring for new apartment', status: 'Confirmed', price: 25000, createdAt: '2025-03-28' },
  { id: 'b2', artisanId: 'a2', artisanName: 'Ngozi Eze', artisanProfession: 'Plumbing Specialist', artisanAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Ngozi', customerName: 'You', date: '2025-04-05', time: '2:00 PM', description: 'Leaking kitchen faucet repair', status: 'Completed', price: 4000, createdAt: '2025-03-25' },
  { id: 'b3', artisanId: 'a6', artisanName: 'Emeka Nwankwo', artisanProfession: 'General Contractor', artisanAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Emeka', customerName: 'You', date: '2025-04-20', time: '8:00 AM', description: 'Home renovation consultation', status: 'Pending', price: 0, createdAt: '2025-04-01' },
  { id: 'b4', artisanId: 'a4', artisanName: 'Musa Bello', artisanProfession: 'Carpenter & Furniture Maker', artisanAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Musa', customerName: 'You', date: '2025-03-15', time: '11:00 AM', description: 'Custom dining table order', status: 'Completed', price: 50000, createdAt: '2025-03-01' },
  { id: 'b5', artisanId: 'a8', artisanName: 'Tunde Mustapha', artisanProfession: 'AC Technician', artisanAvatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=TundeM', customerName: 'You', date: '2025-04-15', time: '9:00 AM', description: 'Split AC installation in bedroom', status: 'Confirmed', price: 20000, createdAt: '2025-04-02' },
];

export const SAMPLE_USER: UserProfile = {
  id: 'u1',
  name: 'Kelechi Okafor',
  email: 'kelechi.o@email.com',
  phone: '+234 812 345 6789',
  avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Kelechi',
  role: 'customer',
  location: 'Lagos, Nigeria',
  memberSince: 'January 2025',
};

export const CITIES = ['Lagos', 'Abuja', 'Port Harcourt', 'Ibadan', 'Kaduna', 'Enugu', 'Kano', 'Benin City'];

export const DEFAULT_FILTERS = {
  query: '',
  category: 'all',
  location: '',
  minPrice: 0,
  maxPrice: 200000,
  minRating: 0,
  availableOnly: false,
  sortBy: 'rating' as const,
};